const ROOMDATASSID = "1ueS2f_zy8cHRaKCXPgDzDZFRHOaKU34vi9qr5i6J3LA"
const ROOMDATASHEETNAME = "Data"
const ROOMDATAHEADERROW = 1

const ROOMUSAGELISTSFOLDERID = "1Ew6a1zJpCZf9SIeel7riPbgQ-FYdJhbE"

const ROOMUSAGELISTTEMPLATEFILEID = "1bif16VyECQ0zKYyku6YZhXhYTI-2mdw0e6iocGBnQ0k"
const ROOMUSAGELISTSHEETNAME = "Raumbenützungsliste"
const ROOMUSAGELISTDISTRICTROW = 1
const ROOMUSAGELISTDISTRICTCOL = 10

const NODISTRICTNAME = "Keine Zweigstelle"

