//Logger.log("Load CT")

//SHEET NAMES AND SHEETS
const COURSETABLEFILENAME = "Kursliste";
const COURSETABLESHEETNAME = "Kursübersicht";
const COURSEBILLINGSHEETNAME = "Kursverrechnung";
const TEACHERBILLINGSHEETNAME = "Lehrerverrechnung";
const DATESSHEETNAME = "Sonstiges";
const IMPORTPAYMENTSHEETNAME = "Zahlungsimport";

const DATASOURCESFOLDERNAME = "Datenquellen";
const DATSOURCESFOLDERIS = "1DrVV2cLEns0cpWSys3hqqreMZNqN5QfM"
const ARCHIVEFOLDERID = "1_kLXIfPRkGY1i7uxNAcVmPS0M9SxFju5"

let COURSETABLESS;
try {
  COURSETABLESS = UTLS.getFile(COURSETABLEFILENAME);
} catch (e) {
  console.error("[CT]Error when importing COURSETABLESS. Trying again. " + e.message);
  COURSETABLESS = UTLS.getFile(COURSETABLEFILENAME);
}

const COURSESHEET = COURSETABLESS.getSheetByName(COURSETABLESHEETNAME);
const COURSEBILLINGSHEET = COURSETABLESS.getSheetByName(COURSEBILLINGSHEETNAME);
const TEACHERBILLINGSHEET = COURSETABLESS.getSheetByName(TEACHERBILLINGSHEETNAME);
const DATESSHEET = COURSETABLESS.getSheetByName(DATESSHEETNAME);
const IMPORTPAYMENTSHEET = COURSETABLESS.getSheetByName(IMPORTPAYMENTSHEETNAME);

//URLS
BASEURLL = "https://docs.google.com/spreadsheets/d/" + COURSESHEET.getParent().getId() + "/edit#gid=";
COURSESHEETBASEURL = BASEURLL + COURSESHEET.getSheetId();
COURSEBILLINGSHEETBASEURL = BASEURLL + COURSEBILLINGSHEET.getSheetId();

//CONSTANTS
//colors
const YELLOW = "#fce8b2";
const RED = "#f4c7c3";
const GREEN = "#b7e1cd";
//STATUS STATMENTS
const PAYMENTSTATUSNOTDUE = "nicht verrechnet";
const PAYMENTSTATUSDUE = "nicht bezahlt";
const PAYMENTSTATUSWRONGAMOUNT = "falscher Betrag";
const PAYMENTSTATUSPAIED = "bezahlt"; //for payments that can not be checked
const PAYMENTSTATUSPAIEDANDNOTCHECKED = "bezahlt & ungeprüft"; //for payments that can be checked
const PAYMENTSTATUSPAIEDANDCHECKED = "bezahlt & geprüft"; //for payments that can be checked

const BILLINGNOTDONESTATUS = "nicht abgeschlossen";
const BILLINGDONESTATUS = "abgeschlossen";

const NOTENTEREDSTATUS = "";

const COURSESTARTEDVALUE = "Kurs läuft";
const NOCOURSEVALUE = "Kein Kurs";
const DEREGISTEREDVALUE = "Abgemeldet";
const COURSEFINISHEDVALUE = "Kurs abgeschlossen";

const BILLINGNOTSENT = "nicht ausgestellt";
const COURSEBILLINGSENT = "Saldo ausgestellt";
const NOCOURSEBILLINGNEEDED = "keine Endverrechnung";
const TRIALLESSONS = 3;
const ADMINFEEMINHOURS = 2;

const NOCOURSEBILLINGNUMBER = "-";

const PREREGWITHADMINFEE = "durch Regiebeitrag"

//ROWS AND COLS
//all sheets
const COURSEIDCOL = 1;
const STUDENTIDCOL = 2;
const TEACHERIDCOL = 3;

const HEADERROW = 5;

const COU_FIRST_DATAROW = 2;
const BIL_FIRST_DATAROW = 6;

//course sheet
const COU_COURSESTATUSCOL = 15;
const COU_COURSEENDDATECOL = 18;

const COU_INSTRUMENT = 11;
const COU_ANMELDUNG = 16;
const COU_EMAIL = 22;
const COU_TELEFONMOBIL = 20;
const COU_TELEFONVORMITTAG = 21;
const COU_RECHNUNGSNAME = 26;
const COU_RECHNUNGSADRESSE = 27;
const COU_RECHNUNGSORT = 28;
const COU_RECHNUNGSPLZ = 29;
const COU_RECHNUNGSMAIL = 25;
const COU_WOHNGEMEINDE = 30;
const COU_GEBURTSDATUM = 23;
const COU_SCHULEKLASSE = 24;

const COU_TEACHERMAIL = 6;
const COU_TEACHERBILLING = 31;
const COU_TEACHERADRESS = 32;
const COU_TEACHERPLZ = 33;
const COU_TEACHERORT = 34;
const COU_TEACHERIBAN = 35;
const COU_TEACHERBIC = 36;
const COU_TEACHERBANK = 37;
const COU_TEACHERIBANMBS = 38;
const COU_TEACHERTEL = 39;

//course billing sheet
const BIL_ADMINFEESTATUSCOL = 12;
const BIL_ADMINBOOKINGCOL = 14;
const BIL_ADMINADMOUNTCOL = 16;
const BIL_ADMINDATECOL = 17;
const BIL_ADMINREFCOL = 18;

const BIL_COURSESTATUSCOL = 11;
const BIL_REMINDERCHECKBOXCOL = 43;
const BIL_INFRACHECKBOXCOL = 44;

const BIL_P1DUECOL = 21;
const BIL_P1BOOKINGCOL = 20;
const BIL_P2DUECOL = 27;
const BIL_P2BOOKINGCOL = 26;
const BIL_P3DUECOL = 33;
const BIL_P3BOOKINGCOL = 32;
const BIL_P4DUECOL = 39;
const BIL_P4BOOKINGCOL = 38;
const BIL_PSALDODUECOL = 47;
const BIL_PSALDOBOOKINGCOL = 46;

const BIL_BILLINGSTATUS = 51;
const BIL_SALSOSENTSTATUSCOL = 52;
const BIL_PAIDSTATUS = 53;

const BIL_PREREGCOL = 54;

const BIL_PRICEPERHOUR = 55;
const BIL_EXPECTEDCOURSEHOURS = 56;
const BIL_EXPECTEDTOTALAMOUNTDUE = 57;
const BIL_EXPECTEDSALDOAMOUNTDUE = 58;
const BIL_CURRENTCOURSEHOURS = 59;
const BIL_CURRENTDUEAMOUNT = 60;
const BIL_CURRENTPAIDAMOUNT = 61;
const BIL_CURRENTSALDOAMOUNT = 62;

const BIL_FINALCOURSEHOURS = 63;
const BIL_DATESSTRING = 64;
const BIL_TEACHERPAYMENTNUMNER = 65;
const BIL_ADMINFEEPAYMENTID = 66;
const BIL_PARTIALPAYMENT1ID = 67;
const BIL_PARTIALPAYMENT2ID = 68;
const BIL_PARTIALPAYMENT3ID = 69;
const BIL_PARTIALPAYMENT4ID = 70;
const BIL_PARTIALPAYMENT5ID = 71;

//teacher billing sheet
const TEA_IDCOL = 1;
const TEA_MAZDUECOL = 9;
const TEA_VOMDUECOL = 18;
const TEA_ROOMCOL = 37;

const TEA_MAZBOOKINGNUMBERCOL = 10;
const TEA_MAZAMOUNTCOL = 12;
const TEA_MAZDATECOL = 13;
const TEA_MAZREFCOL = 14;
const TEA_VOMBOOKINGNUMBERCOL = 19;
const TEA_VOMAMOUNTCOL = 21;
const TEA_VOMDATECOL = 22;
const TEA_VOMREFCOL = 23;
const TEA_OFFICEISDUECOL = 27;
const TEA_OFFICEBOOKINGNUMBERCOL = 28;
const TEA_OFFICEAMOUNTDUECOL = 29;
const TEA_OFFICEAMOUNTCOL = 30;
const TEA_OFFICEDATECOL = 31;
const TEA_OFFICEREFCOL = 32;
const TEA_NUMSTUDENTSCOL = 35;
const TEA_OFFICEROINVOICENUMBERCOL = 36
 
const TEA_MAZPAYMENTID = 36;
const TEA_VOMPAYMENTID = 37;
const TEA_OFFICEPAYMENTID = 38;
//datessheet
const DATES_PAYMENT1DATEROW = 1;
const DATES_PAYMENT2DATEROW = 2;
const DATES_PAYMENT3DATEROW = 3;
const DATES_PAYMENT4DATEROW = 4;
const DATES_SALDOPAYMENT = 5;
const DATES_REMINDER1DATEROW = 6;
const DATES_REMINDER2DATEROW = 7;
const DATES_ASSDATEROW = 8;
const DATES_ROOMDATEROW = 9;
const DATES_OFFICEDATEROW = 10;
const DATES_ADMINFEEROW = 11;

const DATES_BILLCYCLEROW = 15;
